### ISSUE TITLE
Gilded Enhancement does not show "+$5" when it gives the money

### ISSUE THREAD

**Issue by OppositeWolf770** [RattlingSnow353/Familiar#3]
Other enhancements (Like Gold Card) show a popup with the amount of money gained. From my experience, this does not happen with gilded cards.

**Comment by OppositeWolf770** [comment]
It doesn't look like the description counts down after each use, either.

**Comment by OppositeWolf770** [comment]
Another weird thing I noticed. One of my gilded cards turned into a steel card, but the description showed X0 mult and it still had the gilded texture. I'm assuming this is due to it being a multisuit card?
![image](https://github.com/user-attachments/assets/fd504f58-c589-44f8-90ab-33538ccc27d8)

**Comment by RattlingSnow353** [comment]
> Other enhancements (Like Gold Card) show a popup with the amount of money gained. From my experience, this does not happen with gilded cards.

> Another weird thing I noticed. One of my gilded cards turned into a steel card, but the description showed X0 mult and it still had the gilded texture. I'm assuming this is due to it being a multisuit card? 

fixed both of these
