### ISSUE TITLE
Duplicate "Hermes" card in a Pantheon Tin

### ISSUE THREAD

**Issue by OppositeWolf770** [RattlingSnow353/Familiar#4]
I don't know if this is intentional, but when opening a Pantheon Tin, there were two instances of the Hermes card. I do not have Showman as one of my Jokers
![image](https://github.com/user-attachments/assets/23fdc1df-d721-4fce-855d-9546532e7164)

**Comment by OppositeWolf770** [comment]
Well, I found some more instances of this, so I'm leaning more towards intentional.
![image](https://github.com/user-attachments/assets/d6d9d1fc-6296-48df-b23d-361019c28afc)

**Comment by RattlingSnow353** [comment]
i was aware of the bug when i released it, just didn't feel like fixing it atm. i'll get to it later
