### ISSUE TITLE
The Harlot - Unable to use when the card to be generated will replace the harlot card being used

### ISSUE THREAD

**Issue by OppositeWolf770** [RattlingSnow353/Familiar#5]
For example, I'm using the Ghost Deck which only has one consumeable slot. It won't let me use the Harlot because the only spot is taken up by The Harlot.
![image](https://github.com/user-attachments/assets/bdc84776-1097-4501-8909-c1fff04473bc)
The Fool, however, lets you use it in this instance, and I think this may have been the intended behavior.

**Comment by RattlingSnow353** [comment]
fixed this and verdict's use condition
